### ISSUE TITLE
better arg parse

### ISSUE THREAD

**Issue by sambattalio** [sambattalio/chad_stride#13]
fix this

**Comment by AndroidKitKat** [comment]
nou

**Comment by ginglis13** [comment]
could use getopt 

http://man7.org/linux/man-pages/man3/getopt.3.html

**Comment by sambattalio** [comment]
wtf I didn't know that was a thing thanks @ginglis13

**Comment by ginglis13** [comment]
@sambattalio i'd say it's the most chad option
