### ISSUE TITLE
Add a chadstride man page

### ISSUE THREAD

**Issue by sambattalio** [sambattalio/chad_stride#37]
https://www.cyberciti.biz/faq/linux-unix-creating-a-manpage/

**Comment by sambattalio** [comment]
Basically you would just need a more in depth description of the flags and usage of the command.

**Comment by Nuolong** [comment]
#39

**Comment by Nuolong** [comment]
Made some changes to the man page's formatting, and added Makefile lines to install the man page with much help from @pbui !

**Comment by sambattalio** [comment]
POG, shipping it
