### ISSUE TITLE
Bool'in?

### ISSUE THREAD

**Issue by sambattalio** [sambattalio/chad_stride#8]
We should probably add bool's instead of just integers

**Comment by AndroidKitKat** [comment]
where

**Comment by sambattalio** [comment]
the flag variables that aren't SIZE

**Comment by sambattalio** [comment]
@AndroidKitKat https://github.com/sambattalio/chad_stride/blob/dcba5e17f5b7ab3d3cead83c49e9f88b63d4936e/chad_stride.c#L11

**Comment by AndroidKitKat** [comment]
Aren't bools just ints under the hood. We need to do some optimization tests.

**Comment by sambattalio** [comment]
I guess we can #DEFINE true 1 lol

**Comment by sambattalio** [comment]
fixed
